### ISSUE TITLE
Version 1.1.1 crashes on a server install

### ISSUE THREAD

**Issue by sarcastic6** [ByThePowerOfScience/DivineJourney2Addons#1]
When using version 1.1.1 from Curseforge with DJ2 2.15.0, a dedicated server crashes during launch.  When installed on a client, it launches fine.

Crash log follows:
[crash-2022-08-11_23.40.05-server.txt](https://github.com/ByThePowerOfScience/DivineJourney2Addons/files/9313552/crash-2022-08-11_23.40.05-server.txt)
[debug.log](https://github.com/ByThePowerOfScience/DivineJourney2Addons/files/9313555/debug.log)

I can replicate this with a clean install of the pack and just replacing version 1.1.0 with 1.1.1.

**Comment by ByThePowerOfScience** [comment]
Could you please run the program with the JVM args `-Dforge.console.logging.level=debug -Dmixin.debug.export=true -Dmixin.debug.verbose=true` and send me both the log and the `<minecraft dir>/.mixin.out/pokefenn/totemic/init/ModContent.class` file?

**Comment by sarcastic6** [comment]
I've added those args, but I don't have exactly what you asked for.  Inside .mixin.out, there are only two folders, "class" and "audit".  Inside class there are folders for other mods (thaumcraft, botania, mekanism, etc) but not pokefenn/totemic/etc.

The debug log follows.  The crash report file is identical to the previous one, so including it again would be redundant.
[debug.log](https://github.com/ByThePowerOfScience/DivineJourney2Addons/files/9334106/debug.log)

By the way, does com.mojang.realmsclient.util.Pair exist server-side?  I was poking around the source from some other mods and it looks like they use org.apache.commons.lang3.tuple.Pair instead.

**Comment by ByThePowerOfScience** [comment]
> By the way, does com.mojang.realmsclient.util.Pair exist server-side? I was poking around the source from some other mods and it looks like they use org.apache.commons.lang3.tuple.Pair instead.

That's exactly the issue!  I'll change it out ASAP.  Thanks!
